# ========== DOSYA: applications/pyproject.toml ==========
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azuraforge-applications-catalog"
version = "0.1.0"
description = "A catalog of official applications for the AzuraForge platform."
